sequenceDiagram
    participant Medarbejder as Medarbejder
    participant System as System

     %% Use Case 3: Kunde køber spil
    Medarbejder->>System: Slet spil fra lager efter køb
    System-->>Medarbejder: Bekræftelse på fjernelse