sequenceDiagram
    participant Medarbejder as Medarbejder
    participant System as System

      %% Use Case 2: Tilføjelse af nye spil
    Medarbejder->>System: Tilføj nyt spil (navn, genre, stand, pris, antal)
    System-->>Medarbejder: Bekræftelse på oprettelse
    Medarbejder->>System: Opdater stand af spil (nyStand, nyPris)
    System-->>Medarbejder: Bekræftigelse på opdatering
